ali_datatable:
    all:
        action:           true
        search:           true
    js:
        iDisplayLength: "25"
        aLengthMenu: "[[5,10, 25, 50, 100, 500], [5,10, 25, 50, 100, 500]]"
        bJQueryUI: "false"
        bStateSave: "true"
