# Assetic Configuration
assetic:
    debug:          false #"%kernel.debug%"
    use_controller: false
    bundles:
      - CwdAdminMetronicBundle
      - AspetosLegacyBundle
      - AspetosAdminBundle
      - AspetosFrontendBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #less:
        #    apply_to: "*.less"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
