genemu_form:
    select2:
        enabled: true
    recaptcha:
        enabled:              true
        public_key:           6LeuffsSAAAAALzJBQdfrcekkqftp6ZiY7HbB9T3
        private_key:          6LeuffsSAAAAAHmnotUoOQscWPc-bzgAlcBQXB3t
        configs:
            theme: 'clean'
            lang: 'de'
