jms_di_extra:
    locations:
        all_bundles: false
        bundles:
            - "CwdAdminMetronicBundle"
            - "CwdGenericBundle"
            - "AspetosAdminBundle"
            - "AspetosFrontendBundle"
            - "AspetosLegacyBundle"
            - "AspetosShopBundle"
        directories:
            - "%kernel.root_dir%/../src/Aspetos/Service"
