rollerworks_password_strength:
    blacklist:
        default_provider: rollerworks_password_strength.blacklist.provider.array
        providers:
            array:
                - passwort
                - password
                - geheim
                - secret
                - aspetos
                - 123456789
                - 1234578
                - 123456
                - qwerty
                - qwertz
                - baseball
                - football
                - monkey
                - letmein
                - mustang
                - access
                - shadow
                - master
                - supermann
                - batman
                - 123123
                - trustno1
                - passw0rd
