stof_doctrine_extensions:
    default_locale: de_DE
    class:
        sluggable: Cwd\GenericBundle\Doctrine\SluggableListener
    orm:
        default:
            tree: false
            sortable: true
            softdeleteable: true
            timestampable: true
            blameable: true
            loggable: true
            sluggable: true
