imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: config/ali_datatable.yml }
    - { resource: config/assetic.yml }
    - { resource: config/braincrafted_bootstrap.yml }
    - { resource: config/cwd_generic.yml }
    - { resource: config/cwd_vtiger.yml }
    - { resource: config/doctrine.yml }
    - { resource: config/framework.yml }
    - { resource: config/genemu_form.yml }
    - { resource: config/gregwar_image.yml }
    - { resource: config/jms_di_extra.yml }
    - { resource: config/jms_security_extra.yml }
    - { resource: config/knp_menu.yml }
    - { resource: config/stof_doctrine_extensions.yml }
    - { resource: config/swiftmailer.yml }
    - { resource: config/twig.yml }
