imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "en" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
      app_name:       "Aspetos"
      app_version:    "2.0.1"
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
          - AspetosAdminBundle:Layout:bootstrap.html.twig

# Assetic Configuration
assetic:
    debug:          false #"%kernel.debug%"
    use_controller: false
    bundles:
      - CwdAdminMetronicBundle
      - AspetosLegacyBundle
      - AspetosAdminBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #less:
        #    apply_to: "*.less"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        types:
            #phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    enum: string
            legacy:
                driver:   "%database_legacy_driver%"
                host:     "%database_legacy_host%"
                port:     "%database_legacy_port%"
                dbname:   "%database_legacy_name%"
                user:     "%database_legacy_user%"
                password: "%database_legacy_password%"
                charset:  UTF8
                mapping_types:
                    enum: string
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                  entity_listener_resolver: cwd.generic.doctrine.entity_listener_resolver
                  connection: default
                  dql:
                      string_functions:
                          group_concat: Cwd\GenericBundle\Doctrine\Extensions\GroupConcat
                          date: Cwd\GenericBundle\Doctrine\Extensions\Date
                  auto_mapping: false
                  mappings:
                      model:
                        type: "annotation"
                        dir:  %kernel.root_dir%/../src/Aspetos/Model/Entity
                        prefix: Aspetos\Model\Entity
                        alias:  Model
                        is_bundle: false
                      cwd:
                        type: "annotation"
                        is_bundle: false
                        alias: Cwd
                        dir:  %kernel.root_dir%/../src/Cwd/MediaBundle/Model/Entity
                        prefix: Cwd\MediaBundle\Model\Entity
                      #Doctrine Extensions Mappings
                      gedmo_translatable:
                          type: annotation
                          prefix: Gedmo\Translatable\Entity
                          dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                          alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                          is_bundle: false
                      gedmo_translator:
                          type: annotation
                          prefix: Gedmo\Translator\Entity
                          dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                          alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                          is_bundle: false
                      gedmo_loggable:
                          type: annotation
                          prefix: Gedmo\Loggable\Entity
                          dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                          alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                          is_bundle: false
                  filters:
                      softdeleteable:
                          class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                          enabled: true
            legacy:
                  connection: legacy
                  auto_mapping: false
                  mappings:
                      model:
                          type: "annotation"
                          dir:  %kernel.root_dir%/../src/Aspetos/Bundle/LegacyBundle/Model/Entity
                          prefix: Aspetos\Bundle\LegacyBundle\Model\Entity
                          alias:  Legacy
                          is_bundle: false


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_menu:
    twig:
        template: AspetosAdminBundle:Menu:main.html.twig
    templating: false
    default_renderer: twig

jms_di_extra:
    locations:
        all_bundles: false
        bundles:
            - "CwdAdminMetronicBundle"
            - "CwdGenericBundle"
            - "AspetosAdminBundle"
            - "AspetosLegacyBundle"
        directories:
            - "%kernel.root_dir%/../src/Aspetos/Service"

braincrafted_bootstrap:
    auto_configure:
        assetic: false
        twig: false

genemu_form:
    select2:
        enabled: true
    recaptcha:
        enabled:              true
        public_key:           6LeuffsSAAAAALzJBQdfrcekkqftp6ZiY7HbB9T3
        private_key:          6LeuffsSAAAAAHmnotUoOQscWPc-bzgAlcBQXB3t
        configs:
            theme: 'clean'
            lang: 'de'

jms_security_extra:
    secure_all_services: false
    enable_iddqd_attribute: false
    expressions: true

ali_datatable:
    all:
        action:           true
        search:           true
    js:
        iDisplayLength: "25"
        aLengthMenu: "[[5,10, 25, 50, 100, 500], [5,10, 25, 50, 100, 500]]"
        bJQueryUI: "false"
        bStateSave: "true"

stof_doctrine_extensions:
    default_locale: de_DE
    orm:
        default:
            tree: false
            sortable: true
            softdeleteable: true
            timestampable: true
            blameable: true
            loggable: true
            sluggable: true

cwd_generic:
    from_name: "Hostmaster"
    from_email: "hostmaster@cwd.at"
    form_extension_autorequire_enabled: true

cwd_vtiger:
    apiurl: "http://crm2.aspetos.com/webservice.php"
    username: "ludwig.ruderstaller"
    accesskey: "oDKnlwoTCQyHXTn"

gregwar_image:
    throw_exception: %kernel.debug%
