aspetos_legacy_admin:
    resource: "@AspetosLegacyBundle/Controller/"
    type:     annotation
    prefix:   /admin/legacy

aspetos_admin:
    resource: "@AspetosAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
