# redirecting the admin home
root:
    path: /
    defaults:
        _controller:    FrameworkBundle:Redirect:redirect
        route:          aspetos_frontend_default_index
        country:        at

aspetos_legacy_admin:
    resource:   "@AspetosLegacyBundle/Controller/"
    type:       annotation
    prefix:     /admin/legacy

# admin-specific FOSUser routing
admin_login:
    path:  /admin/login
    defaults: { _controller: "FOSUserBundle:Security:login" }

admin_login_check:
    path:  /admin/login_check
    defaults: { _controller: "FOSUserBundle:Security:check" }

admin_logout:
    path:  /admin/logout
    defaults: { _controller: "FOSUserBundle:Security:logout" }

admin_profile_show:
    path:  /admin/profile
    defaults: { _controller: "FOSUserBundle:Profile:show" }

admin_profile_edit:
    path:  /admin/profile/edit
    defaults: { _controller: "FOSUserBundle:Profile:edit" }

# general FOSUser routing
fos_user_security:
    resource:   "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:     /

fos_user_resetting:
    resource:   "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:     /resetting

fos_user_profile:
    resource:   "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:     /profile

fos_user_register:
    resource:   "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:     /register

fos_user_change_password:
    resource:   "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:     /profile/password


lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /admin/translation

aspetos_admin:
    resource:   "@AspetosAdminBundle/Controller/"
    type:       annotation
    prefix:     /admin

#aspetos_frontend_index:
#    path:       /
#    defaults:
#        _controller: FrameworkBundle:Redirect:urlRedirect
#        path: /at
#        permanent: true

aspetos_frontend:
    resource:   "@AspetosFrontendBundle/Controller/"
    type:       annotation
    prefix:     /{country}
    defaults:   {country: at}
    requirements:
        country: at|de

aspetos_shop:
    resource: "@AspetosShopBundle/Controller/"
    type:     annotation
    prefix:   /
