services:
    # aliases for auto-wiring
    container: @service_container
    em: @doctrine.orm.entity_manager
    entity_manager: @doctrine.orm.entity_manager
    legacy_entity_manager: @doctrine.orm.legacy_entity_manager
    dispatcher: @event_dispatcher
    security: @security.context
    token_storage: @security.token_storage

    aspetos_role_hierarchy:
        alias: security.role_hierarchy

    aspetos.service.authorization.voter.is_owner_with_permission_or_admin:
        class: Aspetos\Service\Authorization\Voter\IsOwnerWithPermissionOrAdminVoter
        tags:
            - { name: security.voter }
        arguments: ["@aspetos_role_hierarchy", "@aspetos.service.permission"]

    ajax.authlistener:
        class: Aspetos\Service\Listener\AjaxAuthenticationListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 255 }
