<?php
/*
 * This file is part of Aspetos
 *
 * (c)2014 Ludwig Ruderstaller <lr@cwd.at>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Aspetos\Tests\Service\DataFixtures;

use Aspetos\Model\Entity\District;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

/**
 * Loads countries data
 */
class LoadDistrictData extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * Load fixtures
     *
     * @param \Doctrine\Common\Persistence\ObjectManager $manager
     */
    public function load(ObjectManager $manager)
    {
        $manager->clear();
        gc_collect_cycles(); // Could be useful if you have a lot of fixtures

        $districts = array(
            array('regionId' => '7','name' => 'Imst'),
            array('regionId' => '7','name' => 'Landeck'),
            array('regionId' => '7','name' => 'Reutte'),
            array('regionId' => '7','name' => 'Innsbruck Land'),
            array('regionId' => '7','name' => 'Innsbruck'),
            array('regionId' => '7','name' => 'Schwaz'),
            array('regionId' => '7','name' => 'Kufstein'),
            array('regionId' => '7','name' => 'Kitzbühel'),
            array('regionId' => '7','name' => 'Lienz'),
            array('regionId' => '8','name' => 'Bludenz'),
            array('regionId' => '8','name' => 'Bregenz'),
            array('regionId' => '8','name' => 'Dornbirn'),
            array('regionId' => '8','name' => 'Feldkirch'),
            array('regionId' => '5','name' => 'Hallein'),
            array('regionId' => '5','name' => 'Stadt Salzburg'),
            array('regionId' => '5','name' => 'Salzburg Umgebung'),
            array('regionId' => '5','name' => 'St. Johann im Pongau'),
            array('regionId' => '5','name' => 'Tamsweg'),
            array('regionId' => '5','name' => 'Zell am See'),
            array('regionId' => '2','name' => 'Feldkirchen'),
            array('regionId' => '2','name' => 'Hermagor'),
            array('regionId' => '2','name' => 'Klagenfurt Land'),
            array('regionId' => '2','name' => 'Klagenfurt Stadt'),
            array('regionId' => '2','name' => 'Spittal an der Drau'),
            array('regionId' => '2','name' => 'St. Veit an der Glan'),
            array('regionId' => '2','name' => 'Villach Land'),
            array('regionId' => '2','name' => 'Villach Stadt'),
            array('regionId' => '2','name' => 'Völkermarkt'),
            array('regionId' => '2','name' => 'Wolfsberg'),
            array('regionId' => '6','name' => 'Bruck an der Mur'),
            array('regionId' => '6','name' => 'Deutschlandsberg'),
            array('regionId' => '6','name' => 'Feldbach'),
            array('regionId' => '6','name' => 'Fürstenfeld'),
            array('regionId' => '6','name' => 'Graz Stadt'),
            array('regionId' => '6','name' => 'Graz Umgebung'),
            array('regionId' => '6','name' => 'Hartberg'),
            array('regionId' => '6','name' => 'Judenburg'),
            array('regionId' => '6','name' => 'Knittelfeld'),
            array('regionId' => '6','name' => 'Leibnitz'),
            array('regionId' => '6','name' => 'Leoben'),
            array('regionId' => '6','name' => 'Liezen'),
            array('regionId' => '6','name' => 'Murau'),
            array('regionId' => '6','name' => 'Mürzzuschlag'),
            array('regionId' => '6','name' => 'Radkersburg'),
            array('regionId' => '6','name' => 'Voitsberg'),
            array('regionId' => '6','name' => 'Weiz'),
            array('regionId' => '4','name' => 'Braunau am Inn'),
            array('regionId' => '4','name' => 'Eferding'),
            array('regionId' => '4','name' => 'Freistadt'),
            array('regionId' => '4','name' => 'Gmunden'),
            array('regionId' => '4','name' => 'Grieskirchen'),
            array('regionId' => '4','name' => 'Kirchdorf an der Krems'),
            array('regionId' => '4','name' => 'Linz Stadt'),
            array('regionId' => '4','name' => 'Linz Land'),
            array('regionId' => '4','name' => 'Perg'),
            array('regionId' => '4','name' => 'Ried im Innkreis'),
            array('regionId' => '4','name' => 'Rohrbach'),
            array('regionId' => '4','name' => 'Schärding'),
            array('regionId' => '4','name' => 'Steyr Stadt'),
            array('regionId' => '4','name' => 'Steyr Land'),
            array('regionId' => '4','name' => 'Urfahr Umgebung'),
            array('regionId' => '4','name' => 'Vöcklabruck'),
            array('regionId' => '4','name' => 'Wels Stadt'),
            array('regionId' => '4','name' => 'Wels Land'),
            array('regionId' => '3','name' => 'Amstetten'),
            array('regionId' => '3','name' => 'Baden'),
            array('regionId' => '3','name' => 'Bruck an der Leitha'),
            array('regionId' => '3','name' => 'Gänserndorf'),
            array('regionId' => '3','name' => 'Gmünd'),
            array('regionId' => '3','name' => 'Hollabrunn'),
            array('regionId' => '3','name' => 'Horn'),
            array('regionId' => '3','name' => 'Korneuburg'),
            array('regionId' => '3','name' => 'Krems Land'),
            array('regionId' => '3','name' => 'Krems Stadt'),
            array('regionId' => '3','name' => 'Lilienfeld'),
            array('regionId' => '3','name' => 'Melk'),
            array('regionId' => '3','name' => 'Mistelbach'),
            array('regionId' => '3','name' => 'Mödling'),
            array('regionId' => '3','name' => 'Neunkirchen'),
            array('regionId' => '3','name' => 'St. Pölten Stadt'),
            array('regionId' => '3','name' => 'St. Pölten Land'),
            array('regionId' => '3','name' => 'Scheibbs'),
            array('regionId' => '3','name' => 'Tulln'),
            array('regionId' => '3','name' => 'Waidhofen an der Thaya'),
            array('regionId' => '3','name' => 'Waidhofen an der Ybbs'),
            array('regionId' => '3','name' => 'Wien Umgebung'),
            array('regionId' => '3','name' => 'Wiener Neustadt Land'),
            array('regionId' => '3','name' => 'Wiener Neustadt Stadt'),
            array('regionId' => '3','name' => 'Zwettl'),
            array('regionId' => '1','name' => 'Eisenstadt Stadt'),
            array('regionId' => '1','name' => 'Eisenstadt Land'),
            array('regionId' => '1','name' => 'Güssing'),
            array('regionId' => '1','name' => 'Jennersdorf'),
            array('regionId' => '1','name' => 'Mattersburg'),
            array('regionId' => '1','name' => 'Neusiedl am See'),
            array('regionId' => '1','name' => 'Oberpullendorf'),
            array('regionId' => '1','name' => 'Oberwart'),
            array('regionId' => '1','name' => 'Rust (Stadt)'),
            array('regionId' => '9','name' => ' 1. Innere Stadt'),
            array('regionId' => '9','name' => ' 2. Leopoldstadt'),
            array('regionId' => '9','name' => ' 3. Landstraße'),
            array('regionId' => '9','name' => ' 4. Wieden'),
            array('regionId' => '9','name' => ' 5. Margareten'),
            array('regionId' => '9','name' => ' 6. Mariahilf'),
            array('regionId' => '9','name' => ' 7. Neubau'),
            array('regionId' => '9','name' => ' 8. Josefstadt'),
            array('regionId' => '9','name' => ' 9. Alsergrund'),
            array('regionId' => '9','name' => '10. Favoriten'),
            array('regionId' => '9','name' => '11. Simmering'),
            array('regionId' => '9','name' => '12. Meidling'),
            array('regionId' => '9','name' => '13. Hietzing'),
            array('regionId' => '9','name' => '14. Penzing'),
            array('regionId' => '9','name' => '15. Fünfhaus'),
            array('regionId' => '9','name' => '16. Ottakring'),
            array('regionId' => '9','name' => '17. Hernals'),
            array('regionId' => '9','name' => '18. Währing'),
            array('regionId' => '9','name' => '19. Döbling'),
            array('regionId' => '9','name' => '20. Brigittenau'),
            array('regionId' => '9','name' => '21. Floridsdorf'),
            array('regionId' => '9','name' => '22. Donaustadt'),
            array('regionId' => '9','name' => '23. Liesing'),
            array('regionId' => '24','name' => 'Flensburg, Kreisfreie Stadt'),
            array('regionId' => '24','name' => 'Kiel, Landeshauptstadt, Kreisfreie Stadt'),
            array('regionId' => '15','name' => 'Hamburg'),
            array('regionId' => '24','name' => 'Lübeck, Hansestadt, Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Braunschweig, Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Salzgitter, Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Wolfsburg, Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Gifhorn'),
            array('regionId' => '18','name' => 'Göttingen'),
            array('regionId' => '18','name' => 'Goslar'),
            array('regionId' => '18','name' => 'Helmstedt'),
            array('regionId' => '18','name' => 'Northeim'),
            array('regionId' => '18','name' => 'Osterode am Harz'),
            array('regionId' => '18','name' => 'Peine'),
            array('regionId' => '18','name' => 'Wolfenbüttel'),
            array('regionId' => '18','name' => 'Region Hannover'),
            array('regionId' => '18','name' => 'Hannover, Landeshauptstadt'),
            array('regionId' => '18','name' => 'Diepholz'),
            array('regionId' => '18','name' => 'Hameln-Pyrmont'),
            array('regionId' => '18','name' => 'Hildesheim'),
            array('regionId' => '18','name' => 'Holzminden'),
            array('regionId' => '18','name' => 'Nienburg (Weser)'),
            array('regionId' => '18','name' => 'Schaumburg'),
            array('regionId' => '18','name' => 'Celle'),
            array('regionId' => '18','name' => 'Cuxhaven'),
            array('regionId' => '18','name' => 'Harburg'),
            array('regionId' => '18','name' => 'Lüchow-Dannenberg'),
            array('regionId' => '18','name' => 'Lüneburg'),
            array('regionId' => '18','name' => 'Osterholz'),
            array('regionId' => '18','name' => 'Rotenburg (Wümme)'),
            array('regionId' => '18','name' => 'Heidekreis'),
            array('regionId' => '18','name' => 'Stade'),
            array('regionId' => '18','name' => 'Uelzen'),
            array('regionId' => '18','name' => 'Verden'),
            array('regionId' => '18','name' => 'Delmenhorst, Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Emden, Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Oldenburg (Oldenburg), Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Osnabrück, Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Wilhelmshaven, Kreisfreie Stadt'),
            array('regionId' => '18','name' => 'Ammerland'),
            array('regionId' => '18','name' => 'Aurich'),
            array('regionId' => '18','name' => 'Cloppenburg'),
            array('regionId' => '18','name' => 'Emsland'),
            array('regionId' => '18','name' => 'Friesland'),
            array('regionId' => '18','name' => 'Grafschaft Bentheim'),
            array('regionId' => '18','name' => 'Leer'),
            array('regionId' => '18','name' => 'Oldenburg'),
            array('regionId' => '18','name' => 'Osnabrück'),
            array('regionId' => '18','name' => 'Vechta'),
            array('regionId' => '18','name' => 'Wesermarsch'),
            array('regionId' => '18','name' => 'Wittmund'),
            array('regionId' => '24','name' => 'Neumünster, Kreisfreie Stadt'),
            array('regionId' => '14','name' => 'Bremen, Kreisfreie Stadt'),
            array('regionId' => '14','name' => 'Bremerhaven, Kreisfreie Stadt'),
            array('regionId' => '24','name' => 'Dithmarschen'),
            array('regionId' => '19','name' => 'Düsseldorf, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Duisburg, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Essen, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Krefeld, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Mönchengladbach, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Mülheim an der Ruhr, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Oberhausen, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Remscheid, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Solingen, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Wuppertal, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Kleve, Kreis'),
            array('regionId' => '19','name' => 'Mettmann, Kreis'),
            array('regionId' => '19','name' => 'Rhein-Kreis Neuss'),
            array('regionId' => '19','name' => 'Viersen, Kreis'),
            array('regionId' => '19','name' => 'Wesel, Kreis'),
            array('regionId' => '19','name' => 'Bonn / Rhein-Sieg'),
            array('regionId' => '19','name' => 'Köln, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Leverkusen, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Städteregion Aachen (einschl. Stadt Aachen)'),
            array('regionId' => '19','name' => 'Aachen'),
            array('regionId' => '19','name' => 'Aachen, Kreis'),
            array('regionId' => '19','name' => 'Düren, Kreis'),
            array('regionId' => '19','name' => 'Rhein-Erft-Kreis'),
            array('regionId' => '19','name' => 'Euskirchen, Kreis'),
            array('regionId' => '19','name' => 'Heinsberg, Kreis'),
            array('regionId' => '19','name' => 'Oberbergischer Kreis'),
            array('regionId' => '19','name' => 'Rheinisch-Bergischer Kreis'),
            array('regionId' => '19','name' => 'Bottrop, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Gelsenkirchen, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Münster, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Borken, Kreis'),
            array('regionId' => '19','name' => 'Coesfeld, Kreis'),
            array('regionId' => '19','name' => 'Recklinghausen, Kreis'),
            array('regionId' => '19','name' => 'Steinfurt, Kreis'),
            array('regionId' => '19','name' => 'Warendorf, Kreis'),
            array('regionId' => '19','name' => 'Bielefeld, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Gütersloh, Kreis'),
            array('regionId' => '19','name' => 'Herford, Kreis'),
            array('regionId' => '19','name' => 'Höxter, Kreis'),
            array('regionId' => '19','name' => 'Lippe, Kreis'),
            array('regionId' => '19','name' => 'Minden-Lübbecke, Kreis'),
            array('regionId' => '19','name' => 'Paderborn, Kreis'),
            array('regionId' => '19','name' => 'Bochum, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Dortmund, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Hagen, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Hamm, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Herne, Kreisfreie Stadt'),
            array('regionId' => '19','name' => 'Ennepe-Ruhr-Kreis'),
            array('regionId' => '19','name' => 'Hochsauerlandkreis'),
            array('regionId' => '19','name' => 'Märkischer Kreis'),
            array('regionId' => '19','name' => 'Olpe, Kreis'),
            array('regionId' => '19','name' => 'Siegen-Wittgenstein, Kreis'),
            array('regionId' => '19','name' => 'Soest, Kreis'),
            array('regionId' => '19','name' => 'Unna, Kreis'),
            array('regionId' => '24','name' => 'Herzogtum Lauenburg'),
            array('regionId' => '16','name' => 'Darmstadt, Kreisfreie Stadt'),
            array('regionId' => '16','name' => 'Frankfurt am Main, Kreisfreie Stadt'),
            array('regionId' => '16','name' => 'Offenbach am Main, Kreisfreie Stadt'),
            array('regionId' => '16','name' => 'Wiesbaden, Landeshauptstadt, Kreisfreie Stadt'),
            array('regionId' => '16','name' => 'Bergstraße'),
            array('regionId' => '16','name' => 'Darmstadt-Dieburg'),
            array('regionId' => '16','name' => 'Groß-Gerau'),
            array('regionId' => '16','name' => 'Hochtaunuskreis'),
            array('regionId' => '16','name' => 'Main-Kinzig-Kreis'),
            array('regionId' => '16','name' => 'Main-Taunus-Kreis'),
            array('regionId' => '16','name' => 'Odenwaldkreis'),
            array('regionId' => '16','name' => 'Offenbach'),
            array('regionId' => '16','name' => 'Rheingau-Taunus-Kreis'),
            array('regionId' => '16','name' => 'Wetteraukreis'),
            array('regionId' => '16','name' => 'Gießen'),
            array('regionId' => '16','name' => 'Lahn-Dill-Kreis'),
            array('regionId' => '16','name' => 'Limburg-Weilburg'),
            array('regionId' => '16','name' => 'Marburg-Biedenkopf'),
            array('regionId' => '16','name' => 'Vogelsbergkreis'),
            array('regionId' => '16','name' => 'Kassel, Kreisfreie Stadt'),
            array('regionId' => '16','name' => 'Fulda'),
            array('regionId' => '16','name' => 'Hersfeld-Rotenburg'),
            array('regionId' => '16','name' => 'Kassel'),
            array('regionId' => '16','name' => 'Schwalm-Eder-Kreis'),
            array('regionId' => '16','name' => 'Waldeck-Frankenberg'),
            array('regionId' => '16','name' => 'Werra-Meißner-Kreis'),
            array('regionId' => '24','name' => 'Nordfriesland'),
            array('regionId' => '20','name' => 'Koblenz, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Ahrweiler'),
            array('regionId' => '20','name' => 'Altenkirchen (Westerwald)'),
            array('regionId' => '20','name' => 'Bad Kreuznach'),
            array('regionId' => '20','name' => 'Birkenfeld'),
            array('regionId' => '20','name' => 'Cochem-Zell'),
            array('regionId' => '20','name' => 'Mayen-Koblenz'),
            array('regionId' => '20','name' => 'Neuwied'),
            array('regionId' => '20','name' => 'Rhein-Hunsrück-Kreis'),
            array('regionId' => '20','name' => 'Rhein-Lahn-Kreis'),
            array('regionId' => '20','name' => 'Westerwaldkreis'),
            array('regionId' => '20','name' => 'Trier, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Bernkastel-Wittlich'),
            array('regionId' => '20','name' => 'Eifelkreis Bitburg-Prüm'),
            array('regionId' => '20','name' => 'Vulkaneifel'),
            array('regionId' => '20','name' => 'Trier-Saarburg'),
            array('regionId' => '20','name' => 'Frankenthal (Pfalz), Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Kaiserslautern, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Landau in der Pfalz, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Ludwigshafen am Rhein, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Mainz, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Neustadt an der Weinstraße, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Pirmasens, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Speyer, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Worms, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Zweibrücken, Kreisfreie Stadt'),
            array('regionId' => '20','name' => 'Alzey-Worms'),
            array('regionId' => '20','name' => 'Bad Dürkheim'),
            array('regionId' => '20','name' => 'Donnersbergkreis'),
            array('regionId' => '20','name' => 'Germersheim'),
            array('regionId' => '20','name' => 'Kaiserslautern'),
            array('regionId' => '20','name' => 'Kusel'),
            array('regionId' => '20','name' => 'Südliche Weinstraße'),
            array('regionId' => '20','name' => 'Rhein-Pfalz-Kreis'),
            array('regionId' => '20','name' => 'Mainz-Bingen'),
            array('regionId' => '20','name' => 'Südwestpfalz'),
            array('regionId' => '24','name' => 'Ostholstein'),
            array('regionId' => '10','name' => 'Stuttgart, Landeshauptstadt, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Böblingen'),
            array('regionId' => '10','name' => 'Esslingen'),
            array('regionId' => '10','name' => 'Göppingen'),
            array('regionId' => '10','name' => 'Ludwigsburg'),
            array('regionId' => '10','name' => 'Rems-Murr-Kreis'),
            array('regionId' => '10','name' => 'Heilbronn, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Heilbronn'),
            array('regionId' => '10','name' => 'Hohenlohekreis'),
            array('regionId' => '10','name' => 'Schwäbisch Hall'),
            array('regionId' => '10','name' => 'Main-Tauber-Kreis'),
            array('regionId' => '10','name' => 'Heidenheim'),
            array('regionId' => '10','name' => 'Ostalbkreis'),
            array('regionId' => '10','name' => 'Baden-Baden, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Karlsruhe, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Karlsruhe'),
            array('regionId' => '10','name' => 'Rastatt'),
            array('regionId' => '10','name' => 'Heidelberg, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Mannheim, Universitätsstadt, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Neckar-Odenwald-Kreis'),
            array('regionId' => '10','name' => 'Rhein-Neckar-Kreis'),
            array('regionId' => '10','name' => 'Pforzheim, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Calw'),
            array('regionId' => '10','name' => 'Enzkreis'),
            array('regionId' => '10','name' => 'Freudenstadt'),
            array('regionId' => '10','name' => 'Freiburg im Breisgau, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Breisgau-Hochschwarzwald'),
            array('regionId' => '10','name' => 'Emmendingen'),
            array('regionId' => '10','name' => 'Ortenaukreis'),
            array('regionId' => '10','name' => 'Rottweil'),
            array('regionId' => '10','name' => 'Schwarzwald-Baar-Kreis'),
            array('regionId' => '10','name' => 'Tuttlingen'),
            array('regionId' => '10','name' => 'Konstanz'),
            array('regionId' => '10','name' => 'Lörrach'),
            array('regionId' => '10','name' => 'Waldshut'),
            array('regionId' => '10','name' => 'Reutlingen'),
            array('regionId' => '10','name' => 'Tübingen'),
            array('regionId' => '10','name' => 'Zollernalbkreis'),
            array('regionId' => '10','name' => 'Ulm, Universitätsstadt, Kreisfreie Stadt'),
            array('regionId' => '10','name' => 'Alb-Donau-Kreis'),
            array('regionId' => '10','name' => 'Biberach'),
            array('regionId' => '10','name' => 'Bodenseekreis'),
            array('regionId' => '10','name' => 'Ravensburg'),
            array('regionId' => '10','name' => 'Sigmaringen'),
            array('regionId' => '24','name' => 'Pinneberg'),
            array('regionId' => '11','name' => 'Ingolstadt'),
            array('regionId' => '11','name' => 'München, Landeshauptstadt'),
            array('regionId' => '11','name' => 'Rosenheim, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Altötting'),
            array('regionId' => '11','name' => 'Berchtesgadener Land'),
            array('regionId' => '11','name' => 'Bad Tölz-Wolfratshausen'),
            array('regionId' => '11','name' => 'Dachau'),
            array('regionId' => '11','name' => 'Ebersberg'),
            array('regionId' => '11','name' => 'Eichstätt'),
            array('regionId' => '11','name' => 'Erding'),
            array('regionId' => '11','name' => 'Freising'),
            array('regionId' => '11','name' => 'Fürstenfeldbruck'),
            array('regionId' => '11','name' => 'Garmisch-Partenkirchen'),
            array('regionId' => '11','name' => 'Landsberg am Lech'),
            array('regionId' => '11','name' => 'Miesbach'),
            array('regionId' => '11','name' => 'Mühldorf a.Inn'),
            array('regionId' => '11','name' => 'München'),
            array('regionId' => '11','name' => 'Neuburg-Schrobenhausen'),
            array('regionId' => '11','name' => 'Pfaffenhofen a.d.Ilm'),
            array('regionId' => '11','name' => 'Rosenheim'),
            array('regionId' => '11','name' => 'Starnberg'),
            array('regionId' => '11','name' => 'Traunstein'),
            array('regionId' => '11','name' => 'Weilheim-Schongau'),
            array('regionId' => '11','name' => 'Landshut, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Passau, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Straubing'),
            array('regionId' => '11','name' => 'Deggendorf'),
            array('regionId' => '11','name' => 'Freyung-Grafenau'),
            array('regionId' => '11','name' => 'Kelheim'),
            array('regionId' => '11','name' => 'Landshut'),
            array('regionId' => '11','name' => 'Passau'),
            array('regionId' => '11','name' => 'Regen'),
            array('regionId' => '11','name' => 'Rottal-Inn'),
            array('regionId' => '11','name' => 'Straubing-Bogen'),
            array('regionId' => '11','name' => 'Dingolfing-Landau'),
            array('regionId' => '11','name' => 'Amberg'),
            array('regionId' => '11','name' => 'Regensburg, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Weiden i.d.OPf.'),
            array('regionId' => '11','name' => 'Amberg-Sulzbach'),
            array('regionId' => '11','name' => 'Cham'),
            array('regionId' => '11','name' => 'Neumarkt i.d.OPf.'),
            array('regionId' => '11','name' => 'Neustadt a.d.Waldnaab'),
            array('regionId' => '11','name' => 'Regensburg'),
            array('regionId' => '11','name' => 'Schwandorf'),
            array('regionId' => '11','name' => 'Tirschenreuth'),
            array('regionId' => '11','name' => 'Bamberg, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Bayreuth, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Coburg, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Hof, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Bamberg'),
            array('regionId' => '11','name' => 'Bayreuth'),
            array('regionId' => '11','name' => 'Coburg'),
            array('regionId' => '11','name' => 'Forchheim'),
            array('regionId' => '11','name' => 'Hof'),
            array('regionId' => '11','name' => 'Kronach'),
            array('regionId' => '11','name' => 'Kulmbach'),
            array('regionId' => '11','name' => 'Lichtenfels'),
            array('regionId' => '11','name' => 'Wunsiedel i.Fichtelgebirge'),
            array('regionId' => '11','name' => 'Ansbach, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Erlangen'),
            array('regionId' => '11','name' => 'Fürth, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Nürnberg'),
            array('regionId' => '11','name' => 'Schwabach'),
            array('regionId' => '11','name' => 'Ansbach'),
            array('regionId' => '11','name' => 'Erlangen-Höchstadt'),
            array('regionId' => '11','name' => 'Fürth'),
            array('regionId' => '11','name' => 'Nürnberger Land'),
            array('regionId' => '11','name' => 'Neustadt a.d.Aisch-Bad Windsheim'),
            array('regionId' => '11','name' => 'Roth'),
            array('regionId' => '11','name' => 'Weißenburg-Gunzenhausen'),
            array('regionId' => '11','name' => 'Aschaffenburg, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Schweinfurt, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Würzburg, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Aschaffenburg'),
            array('regionId' => '11','name' => 'Bad Kissingen'),
            array('regionId' => '11','name' => 'Rhön-Grabfeld'),
            array('regionId' => '11','name' => 'Haßberge'),
            array('regionId' => '11','name' => 'Kitzingen'),
            array('regionId' => '11','name' => 'Miltenberg'),
            array('regionId' => '11','name' => 'Main-Spessart'),
            array('regionId' => '11','name' => 'Schweinfurt'),
            array('regionId' => '11','name' => 'Würzburg'),
            array('regionId' => '11','name' => 'Augsburg, Kreisfreie Stadt'),
            array('regionId' => '11','name' => 'Kaufbeuren'),
            array('regionId' => '11','name' => 'Kempten (Allgäu)'),
            array('regionId' => '11','name' => 'Memmingen'),
            array('regionId' => '11','name' => 'Aichach-Friedberg'),
            array('regionId' => '11','name' => 'Augsburg'),
            array('regionId' => '11','name' => 'Dillingen a.d.Donau'),
            array('regionId' => '11','name' => 'Günzburg'),
            array('regionId' => '11','name' => 'Neu-Ulm'),
            array('regionId' => '11','name' => 'Lindau (Bodensee)'),
            array('regionId' => '11','name' => 'Ostallgäu'),
            array('regionId' => '11','name' => 'Unterallgäu'),
            array('regionId' => '11','name' => 'Donau-Ries'),
            array('regionId' => '11','name' => 'Oberallgäu'),
            array('regionId' => '24','name' => 'Plön'),
            array('regionId' => '21','name' => 'Saarbrücken, Regionalverband'),
            array('regionId' => '21','name' => 'Saarbrücken, Landeshauptstadt'),
            array('regionId' => '21','name' => 'Merzig-Wadern'),
            array('regionId' => '21','name' => 'Neunkirchen'),
            array('regionId' => '21','name' => 'Saarlouis'),
            array('regionId' => '21','name' => 'Saarpfalz-Kreis'),
            array('regionId' => '21','name' => 'St. Wendel'),
            array('regionId' => '24','name' => 'Rendsburg-Eckernförde'),
            array('regionId' => '12','name' => 'Berlin'),
            array('regionId' => '24','name' => 'Schleswig-Flensburg'),
            array('regionId' => '13','name' => 'Brandenburg an der Havel, Kreisfreie Stadt'),
            array('regionId' => '13','name' => 'Cottbus, Kreisfreie Stadt'),
            array('regionId' => '13','name' => 'Frankfurt (Oder), Kreisfreie Stadt'),
            array('regionId' => '13','name' => 'Potsdam, Kreisfreie Stadt'),
            array('regionId' => '13','name' => 'Barnim'),
            array('regionId' => '13','name' => 'Dahme-Spreewald'),
            array('regionId' => '13','name' => 'Elbe-Elster'),
            array('regionId' => '13','name' => 'Havelland'),
            array('regionId' => '13','name' => 'Märkisch-Oderland'),
            array('regionId' => '13','name' => 'Oberhavel'),
            array('regionId' => '13','name' => 'Oberspreewald-Lausitz'),
            array('regionId' => '13','name' => 'Oder-Spree'),
            array('regionId' => '13','name' => 'Ostprignitz-Ruppin'),
            array('regionId' => '13','name' => 'Potsdam-Mittelmark'),
            array('regionId' => '13','name' => 'Prignitz'),
            array('regionId' => '13','name' => 'Spree-Neiße'),
            array('regionId' => '13','name' => 'Teltow-Fläming'),
            array('regionId' => '13','name' => 'Uckermark'),
            array('regionId' => '24','name' => 'Segeberg'),
            array('regionId' => '17','name' => 'Greifswald, Kreisfreie Stadt'),
            array('regionId' => '17','name' => 'Neubrandenburg, Kreisfreie Stadt'),
            array('regionId' => '17','name' => 'Rostock, Kreisfreie Stadt'),
            array('regionId' => '17','name' => 'Schwerin, Kreisfreie Stadt'),
            array('regionId' => '17','name' => 'Stralsund, Kreisfreie Stadt'),
            array('regionId' => '17','name' => 'Wismar, Kreisfreie Stadt'),
            array('regionId' => '17','name' => 'Bad Doberan, Kreis'),
            array('regionId' => '17','name' => 'Demmin, Kreis'),
            array('regionId' => '17','name' => 'Güstrow, Kreis'),
            array('regionId' => '17','name' => 'Ludwigslust, Kreis'),
            array('regionId' => '17','name' => 'Mecklenburg-Strelitz, Kreis'),
            array('regionId' => '17','name' => 'Müritz, Kreis'),
            array('regionId' => '17','name' => 'Nordvorpommern, Kreis'),
            array('regionId' => '17','name' => 'Nordwestmecklenburg, Kreis'),
            array('regionId' => '17','name' => 'Ostvorpommern, Kreis'),
            array('regionId' => '17','name' => 'Parchim, Kreis'),
            array('regionId' => '17','name' => 'Rügen, Kreis'),
            array('regionId' => '17','name' => 'Uecker-Randow, Kreis'),
            array('regionId' => '17','name' => 'Landkreis Mecklenburgische Seenplatte'),
            array('regionId' => '17','name' => 'Landkreis Rostock'),
            array('regionId' => '17','name' => 'Landkreis Vorpommern-Rügen'),
            array('regionId' => '17','name' => 'Landkreis Nordwestmecklenburg'),
            array('regionId' => '17','name' => 'Landkreis Vorpommern-Greifswald'),
            array('regionId' => '17','name' => 'Landkreis Ludwigslust-Parchim'),
            array('regionId' => '24','name' => 'Steinburg'),
            array('regionId' => '22','name' => 'Chemnitz, Kreisfreie Stadt'),
            array('regionId' => '22','name' => 'Plauen, Kreisfreie Stadt'),
            array('regionId' => '22','name' => 'Zwickau, Kreisfreie Stadt'),
            array('regionId' => '22','name' => 'Annaberg'),
            array('regionId' => '22','name' => 'Chemnitzer Land'),
            array('regionId' => '22','name' => 'Freiberg'),
            array('regionId' => '22','name' => 'Vogtlandkreis (Chemnitz, Regierungsbezirk)'),
            array('regionId' => '22','name' => 'Mittlerer Erzgebirgskreis'),
            array('regionId' => '22','name' => 'Mittweida'),
            array('regionId' => '22','name' => 'Stollberg'),
            array('regionId' => '22','name' => 'Aue-Schwarzenberg'),
            array('regionId' => '22','name' => 'Zwickauer Land'),
            array('regionId' => '22','name' => 'Dresden, Kreisfreie Stadt'),
            array('regionId' => '22','name' => 'Görlitz, Kreisfreie Stadt'),
            array('regionId' => '22','name' => 'Hoyerswerda, Kreisfreie Stadt'),
            array('regionId' => '22','name' => 'Bautzen'),
            array('regionId' => '22','name' => 'Meißen'),
            array('regionId' => '22','name' => 'Niederschlesischer Oberlausitzkreis'),
            array('regionId' => '22','name' => 'Riesa-Großenhain'),
            array('regionId' => '22','name' => 'Löbau-Zittau'),
            array('regionId' => '22','name' => 'Sächsische Schweiz'),
            array('regionId' => '22','name' => 'Weißeritzkreis'),
            array('regionId' => '22','name' => 'Kamenz'),
            array('regionId' => '22','name' => 'Leipzig, Kreisfreie Stadt'),
            array('regionId' => '22','name' => 'Delitzsch'),
            array('regionId' => '22','name' => 'Döbeln'),
            array('regionId' => '22','name' => 'Leipziger Land'),
            array('regionId' => '22','name' => 'Muldentalkreis'),
            array('regionId' => '22','name' => 'Torgau-Oschatz'),
            array('regionId' => '22','name' => 'Chemnitz, Stadt'),
            array('regionId' => '22','name' => 'Erzgebirgskreis'),
            array('regionId' => '22','name' => 'Landkreis Mittelsachsen'),
            array('regionId' => '22','name' => 'Vogtlandkreis (Direktionsbezirk Chemnitz)'),
            array('regionId' => '22','name' => 'Landkreis Zwickau'),
            array('regionId' => '22','name' => 'Dresden, Stadt'),
            array('regionId' => '22','name' => 'Landkreis Bautzen'),
            array('regionId' => '22','name' => 'Landkreis Görlitz'),
            array('regionId' => '22','name' => 'Landkreis Meißen'),
            array('regionId' => '22','name' => 'Landkreis Sächsische Schweiz-Osterzgebirge'),
            array('regionId' => '22','name' => 'Leipzig, Stadt'),
            array('regionId' => '22','name' => 'Landkreis Leipzig'),
            array('regionId' => '22','name' => 'Landkreis Nordsachsen'),
            array('regionId' => '24','name' => 'Stormarn'),
            array('regionId' => '23','name' => 'Dessau-Roßlau, Kreisfreie Stadt'),
            array('regionId' => '23','name' => 'Halle (Saale), Kreisfreie Stadt'),
            array('regionId' => '23','name' => 'Magdeburg, Kreisfreie Stadt'),
            array('regionId' => '23','name' => 'Altmarkkreis Salzwedel'),
            array('regionId' => '23','name' => 'Anhalt-Bitterfeld'),
            array('regionId' => '23','name' => 'Börde'),
            array('regionId' => '23','name' => 'Burgenlandkreis'),
            array('regionId' => '23','name' => 'Harz'),
            array('regionId' => '23','name' => 'Jerichower Land'),
            array('regionId' => '23','name' => 'Mansfeld-Südharz'),
            array('regionId' => '23','name' => 'Saalekreis'),
            array('regionId' => '23','name' => 'Salzlandkreis'),
            array('regionId' => '23','name' => 'Stendal'),
            array('regionId' => '23','name' => 'Wittenberg'),
            array('regionId' => '23','name' => 'Dessau, Kreisfreie Stadt'),
            array('regionId' => '23','name' => 'Anhalt-Zerbst, Kreis'),
            array('regionId' => '23','name' => 'Bernburg, Kreis'),
            array('regionId' => '23','name' => 'Bitterfeld, Kreis'),
            array('regionId' => '23','name' => 'Köthen, Kreis'),
            array('regionId' => '23','name' => 'Wittenberg, Kreis'),
            array('regionId' => '23','name' => 'Halle (Saale), Kreisfreie Stadt (Halle, Stat. Regi'),
            array('regionId' => '23','name' => 'Burgenlandkreis (Halle, Stat. Region)'),
            array('regionId' => '23','name' => 'Mansfelder Land, Kreis'),
            array('regionId' => '23','name' => 'Merseburg-Querfurt, Kreis'),
            array('regionId' => '23','name' => 'Saalkreis'),
            array('regionId' => '23','name' => 'Sangerhausen, Kreis'),
            array('regionId' => '23','name' => 'Weißenfels, Kreis'),
            array('regionId' => '23','name' => 'Magdeburg, Kreisfreie Stadt (Stat. Region)'),
            array('regionId' => '23','name' => 'Aschersleben-Staßfurt, Kreis'),
            array('regionId' => '23','name' => 'Bördekreis'),
            array('regionId' => '23','name' => 'Halberstadt, Kreis'),
            array('regionId' => '23','name' => 'Jerichower Land, Kreis'),
            array('regionId' => '23','name' => 'Ohrekreis'),
            array('regionId' => '23','name' => 'Stendal, Kreis'),
            array('regionId' => '23','name' => 'Quedlinburg, Kreis'),
            array('regionId' => '23','name' => 'Schönebeck, Kreis'),
            array('regionId' => '23','name' => 'Wernigerode, Kreis'),
            array('regionId' => '23','name' => 'Altmarkkreis Salzwedel, Kreis'),
            array('regionId' => '25','name' => 'Erfurt, krsfr. Stadt'),
            array('regionId' => '25','name' => 'Gera, krsfr. Stadt'),
            array('regionId' => '25','name' => 'Jena, krsfr. Stadt'),
            array('regionId' => '25','name' => 'Suhl, krsfr. Stadt'),
            array('regionId' => '25','name' => 'Weimar, krsfr. Stadt'),
            array('regionId' => '25','name' => 'Eisenach, krsfr. Stadt'),
            array('regionId' => '25','name' => 'Eichsfeld, Kreis'),
            array('regionId' => '25','name' => 'Nordhausen, Kreis'),
            array('regionId' => '25','name' => 'Wartburgkreis'),
            array('regionId' => '25','name' => 'Unstrut-Hainich-Kreis'),
            array('regionId' => '25','name' => 'Kyffhäuserkreis'),
            array('regionId' => '25','name' => 'Schmalkalden-Meiningen, Kreis'),
            array('regionId' => '25','name' => 'Gotha, Kreis'),
            array('regionId' => '25','name' => 'Sömmerda, Kreis'),
            array('regionId' => '25','name' => 'Hildburghausen, Kreis'),
            array('regionId' => '25','name' => 'Ilm-Kreis'),
            array('regionId' => '25','name' => 'Weimarer Land, Kreis'),
            array('regionId' => '25','name' => 'Sonneberg, Kreis'),
            array('regionId' => '25','name' => 'Saalfeld-Rudolstadt, Kreis'),
            array('regionId' => '25','name' => 'Saale-Holzland-Kreis'),
            array('regionId' => '25','name' => 'Saale-Orla-Kreis'),
            array('regionId' => '25','name' => 'Greiz, Kreis'),
            array('regionId' => '25','name' => 'Altenburger Land, Kreis'),
            array('regionId' => '18','name' => 'Achim'),
            array('regionId' => '19','name' => 'Rhein-Sieg-Kreis')
        );

        $regionRep = $manager->getRepository('Model:Region');

        $loopCount = 0;
        foreach ($districts as $district) {
            ++$loopCount;
            $districtObj = new District();
            $districtObj
                ->setName($district['name'])
                ->setRegion($regionRep->find($district['regionId']));

            $manager->persist($districtObj);

            if($loopCount == 2) {
                break;
            }
        }

        $manager->flush();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {
        return 3; // the order in which fixtures will be loaded
    }
}
