---
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Ensure MySQL packages are installed.
  apt: "name={{ item }} state=installed"
  with_items: mysql_packages
