doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:  pdo_sqlite
                user:    test
                path:    %kernel.root_dir%/../var/sqlite.db.cache
                memory: true
                charset: utf8
            legacy:
                driver:  pdo_sqlite
                user:    test
                path:    %kernel.root_dir%/../var/sqlite.legacy.db.cache
                memory: true
                charset: utf8
    orm:
        entity_managers:
            default:
                #metadata_cache_driver: apc
                #query_cache_driver:    apc
                #result_cache_driver:   apc
