services:
    # Backward compatible alias
    aspetos.service.supplier.supplier: @aspetos.service.supplier


    admin.menu_builder:
        class:      Aspetos\Bundle\AdminBundle\Menu\MenuBuilder
        arguments:
            - @knp_menu.factory
            - @security.authorization_checker
            - @event_dispatcher
            - @request_stack
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: admin }

    switch_entity:
        class:      Aspetos\Bundle\AdminBundle\Forms\Type\SwitchEntityType
        tags:
            - { name: form.type }
    switch:
        class:      Aspetos\Bundle\AdminBundle\Forms\Type\SwitchType
        arguments:
            - @translator
        tags:
            - { name: form.type }

    aspetos_admin_form_mortician_media:
        class: Aspetos\Bundle\AdminBundle\Forms\Mortician\MediaType
        tags:
            - { name: form.type }

    aspetos_admin_twig_user_type_color:
        class: Aspetos\Bundle\AdminBundle\Twig\UserTypeColorExtension
        tags:
            - { name: twig.extension }
