services:
    frontend.menu_builder:
        class:      Aspetos\Bundle\FrontendBundle\Menu\MenuBuilder
        arguments:
            - @knp_menu.factory
            - @security.authorization_checker
            - @event_dispatcher
            - @request_stack
            - @cwd.wordpressapi
            - '%wp_menu_news_id%'
            - '%wp_menu_footer_id%'
        tags:
            - { name: knp_menu.menu_builder, method: createFooterMenu, alias: footer }
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createTopBarMenu, alias: top_bar }

    frontend.twig.wordpress:
        class: Aspetos\Bundle\FrontendBundle\Twig\WordpressExtension
        arguments: [@cwd.wordpressapi]
        tags:
            - { name: twig.extension }
